### ISSUE TITLE
It looks like Apple changed the result of number_processors for Sys::Info::Driver::OSX::Device::CPU for M1 CPUs (Macmini9,1)

### ISSUE THREAD

**Issue by MSchienle** [burak/CPAN-Sys-Info-Driver-OSX#2]
On an Intel Core i7 MacBook Pro running Big Sur, I get the following result from Data::Dumper of $cpu from:
my($cpu) = system_profiler( 'SPHardwareDataType' );

'number_processors' => '4',
'SMC_version_system' => '2.19f12',
'l2_cache_core' => '256 KB',
'boot_rom_version' => '430.0.0.0.0',
'machine_model' => 'MacBookPro11,3',
'platform_cpu_htt' => 'htt_enabled',
'packages' => '1',
'current_processor_speed' => '2.3 GHz',
'_name' => 'hardware_overview',
'cpu_type' => 'Quad-Core Intel Core i7',
'provisioning_UDID' => 'F8D4A0B7-C544-5392-953B-FC1CDFD8351A',
'platform_UUID' => 'F8D4A0B7-C544-5392-953B-FC1CDFD8351A',
'serial_number' => 'C02LQ11AFD59',
'machine_name' => 'MacBook Pro',
'l3_cache' => '6 MB',
'physical_memory' => '16 GB'

On an Apple M1 Mac Mini running Big Sur, I get the following result from Data::Dumper of $cpu from:
my($cpu) = system_profiler( 'SPHardwareDataType' );

'_name' => 'hardware_overview',
'serial_number' => 'H2WF30SLQ6NY',
'provisioning_UDID' => '00008103-000654A43A8A001E',
'chip_type' => 'Apple M1',
'boot_rom_version' => '6723.81.1',
'machine_model' => 'Macmini9,1',
'number_processors' => 'proc 8:4:4',
'platform_UUID' => 'FDE32D1F-91B5-580A-B41F-F5E9F35267D3',
'activation_lock_status' => 'activation_lock_enabled',
'physical_memory' => '16 GB',
'machine_name' => 'Mac mini'

Note number_processors on Intel i7 is '4' and on Apple M1 is 'proc 8:4:4'.

This also showed up during installation of the module via cpan:

Running install for module 'Sys::Info'
  BURAK/Sys-Info-0.7811.tar.gz
...
Runtime Requires. 
     Module                 Want   Have. 
     Sys::Info::Base        0.78 0.7807  
     Sys::Info::Driver::OSX 0.78 0.7959  
 
t/00-report-prereqs.t .... ok     
t/03-basic.t ............. 1/? Argument "proc 8:4:4" isn't numeric in foreach loop entry at   /opt/homebrew/Cellar/perl/5.32.1_1/lib/perl5/site_perl/5.32.1/Sys/Info/Driver/OSX/Device/CPU.pm line 84.

**Comment by dkechag** [comment]
FYI a fix is in #3 .

**Comment by burak** [comment]
Released v0.7960
